<?php

namespace Database\Seeders;

use App\Models\Regulation;
use Illuminate\Database\Seeder;

class RegulationSeeder extends Seeder
{
    public function run(): void
    {
        $regulations = [
            // ==========================================
            // KATEGORI: KEPABEANAN & CUKAI (CUSTOMS & IMPORT)
            // ==========================================
            [
                'category' => 'kepabeanan',
                'level' => 'Undang-Undang',
                'code' => 'UU-17-2006-PABEAN',
                'number' => 'UU No. 17 Tahun 2006',
                'year' => 2006,
                'title' => 'Perubahan atas UU No. 10 Tahun 1995 tentang Kepabeanan',
                'about' => 'Dasar Hukum Kepabeanan, Prosedur Impor-Ekspor, Penetapan Nilai Pabean, dan Penetapan Tarif Bea Masuk',
                'status' => 'berlaku',
                'effective_date' => '2006-11-15',
                'summary' => 'Merupakan landasan hukum utama kepabeanan di Indonesia. Mengatur kewajiban importir memberitahukan impor barang menggunakan PIB (Pemberitahuan Impor Barang), penetapan nilai pabean berdasarkan Nilai Transaksi (CIF), dan pengawasan jalur pelayanan kepabeanan.',
                'key_points' => [
                    'Nilai Pabean dihitung dari CIF (Cost + Insurance + Freight) dikonversi ke Rupiah menggunakan Kurs Pajak/Kepabeanan Menkeu saat pendaftaran PIB.',
                    'Pungutan negara atas impor meliputi Bea Masuk, Bea Masuk Tambahan (Anti-Dumping/Safeguard), PPN Impor, PPnBM Impor, dan PPh Pasal 22 Impor.',
                    'Pelunasan kewajiban dilakukan melalui Bukti Penerimaan Negara (BPN) kode billing Modul Impor.',
                    'Klasifikasi pos tarif wajib mengacu pada Harmonized System (HS Code) pada Buku Tarif Kepabeanan Indonesia (BTKI).',
                ],
                'accounting_implications' => 'Bea Masuk dan seluruh biaya pengangkutan/asuransi impor wajib dikapitalisasi ke dalam Nilai Perolehan Persediaan (HPP) barang atau Nilai Perolehan Aset Tetap sesuai PSAK 14/16.',
                'tax_implications' => 'Dokumen PIB yang mencantumkan identitas importir dan dilampiri Surat Setoran Pabean, Cukai dan Pajak (SSPCP) / BPN dipersamakan dengan Faktur Pajak Masukan (dapat dikreditkan di SPT Masa PPN).',
                'keywords' => ['impor', 'pabean', 'bea masuk', 'cif', 'pib', 'sspcp', 'bpn', 'hs code', 'btki', 'jalur hijau', 'jalur merah'],
                'official_source_url' => 'https://jdih.kemenkeu.go.id/fullText/2006/17TAHUN2006UU.HTM',
            ],
            [
                'category' => 'kepabeanan',
                'level' => 'Peraturan Menteri Keuangan',
                'code' => 'PMK-190-2022-IMPOR',
                'number' => 'PMK No. 190/PMK.04/2022',
                'year' => 2022,
                'title' => 'Pengeluaran Barang Impor untuk Dipakai',
                'about' => 'Tata Laksana Pelayanan dan Pengawasan Kepabeanan Pengeluaran Barang Impor untuk Dipakai',
                'status' => 'berlaku',
                'effective_date' => '2023-01-01',
                'summary' => 'Mengatur simplifikasi dan digitalisasi proses impor untuk dipakai, integrasi sistem CEISA 4.0 Bea Cukai dengan Indonesia National Single Window (INSW), serta verifikasi otomatis pembayaran pungutan impor.',
                'key_points' => [
                    'Penyampaian PIB dilakukan secara elektronik mandiri oleh importir atau PPJK berizin.',
                    'Pemeriksaan fisik atau pemindaian x-ray dilakukan secara terarah berdasarkan manajemen risiko profil kepabeanan importir.',
                    'Penerbitan Surat Persetujuan Pengeluaran Barang (SPPB) terbit otomatis setelah seluruh pembayaran bea masuk dan pajak dalam rangka impor (PDRI) terkonfirmasi di kas negara.',
                ],
                'accounting_implications' => 'Persediaan baru dapat diakui di neraca sebagai persediaan fisik dalam gudang saat SPPB terbit dan barang diterima secara fisik dengan Berita Acara / Goods Receipt.',
                'tax_implications' => 'Nomor PIB dan NTPN (Nomor Transaksi Penerimaan Negara) pada SSPCP menjadi kunci validasi e-Faktur Pajak Masukan pada sistem Coretax DJP.',
                'keywords' => ['impor untuk dipakai', 'ceisa', 'insw', 'sppb', 'ppjk', 'pib elektronik', 'ntpn', 'pdri'],
                'official_source_url' => 'https://jdih.kemenkeu.go.id/download/1b62649b-3fe0-4966-9b59-9941914eb130/190~PMK.04~2022Per.pdf',
            ],
            [
                'category' => 'kepabeanan',
                'level' => 'Peraturan Menteri Keuangan',
                'code' => 'PMK-96-2023-KIRIMAN',
                'number' => 'PMK No. 96 Tahun 2023',
                'year' => 2023,
                'title' => 'Ketentuan Kepabeanan, Cukai, dan Pajak atas Impor Barang Kiriman',
                'about' => 'Ambang Batas De Minimis, Tarif Flat Barang Kiriman E-Commerce, dan Perlakuan Komoditas Khusus',
                'status' => 'berlaku',
                'effective_date' => '2023-10-17',
                'summary' => 'Mengatur ketentuan impor barang kiriman pos/kurir dari luar negeri. Menetapkan ambang batas bebas bea masuk (FOB USD 3), perlakuan tarif flat bea masuk 7,5% dan PPN 11% untuk barang umum, serta tarif MFN khusus untuk kosmetik, tas, sepatu, dan tekstil.',
                'key_points' => [
                    'Nilai pabean FOB <= USD 3: Pembebasan Bea Masuk, tetap dikenakan PPN 11%, tidak dipungut PPh 22.',
                    'Nilai pabean FOB > USD 3 s.d USD 1.500: Bea Masuk flat 7,5%, PPN 11%, PPh Pasal 22 dikecualikan.',
                    'Komoditas khusus (tas, sepatu, produk tekstil): Dikenakan tarif MFN (Bea Masuk 15%-25%, PPh 22 7,5%-10%).',
                ],
                'accounting_implications' => 'Biaya pajak dan bea impor barang kiriman yang ditagih kurir (DHL, FedEx, Pos) dicatat sebagai beban operasional / penambah harga beli inventaris kantor.',
                'tax_implications' => 'Bukti bayar kurir (Consignment Note yang memuat billing impor) dapat dipertanggungjawabkan sebagai bukti sah pengeluaran fiskal.',
                'keywords' => ['barang kiriman', 'de minimis', 'fob 3 usd', 'kurir', 'pembelian online luar negeri', 'mfn'],
                'official_source_url' => 'https://jdih.kemenkeu.go.id/download/557f6b92-4e48-4cb5-aa5c-9c716ec89f1d/96%20TAHUN%202023.pdf',
            ],

            // ==========================================
            // KATEGORI: PAJAK (UU & PP PERPAJAKAN)
            // ==========================================
            [
                'category' => 'pajak',
                'level' => 'Undang-Undang',
                'code' => 'UU-7-2021-HPP',
                'number' => 'UU No. 7 Tahun 2021',
                'year' => 2021,
                'title' => 'Harmonisasi Peraturan Perpajakan (UU HPP)',
                'about' => 'Reformasi Menyeluruh KUP, PPh, PPN, Program Pengungkapan Sukarela, Pajak Karbon, dan Cukai',
                'status' => 'berlaku',
                'effective_date' => '2021-10-29',
                'summary' => 'Tonggak utama reformasi perpajakan nasional. Menetapkan NIK sebagai NPWP Orang Pribadi, mengubah bracket tarif PPh Orang Pribadi s.d 35%, menetapkan tarif PPh Badan flat 22%, menaikkan tarif umum PPN menjadi 11% (1 April 2022) dan 12% (1 Januari 2025).',
                'key_points' => [
                    'Tarif PPN Umum: 11% (sejak 1 April 2022) dan dijadwalkan 12%.',
                    'Tarif PPh Badan: Flat 22% dari Penghasilan Kena Pajak.',
                    'Fasilitas Pengurangan Tarif Pasal 31E UU PPh: Diskon 50% atas PKP bagian omzet s.d Rp 4,8 Miliar bagi WP Badan beromzet s.d Rp 50 Miliar.',
                    'Pengaturan Imbalan Natura/Kenikmatan: Objek PPh bagi penerima dan deductible expense bagi pemberi kerja.',
                    'Pemberian sanksi administratif perpajakan yang lebih adil berbasis suku bunga acuan BI + markup.',
                ],
                'accounting_implications' => 'Pengakuan Beban Pajak Kini (Current Tax) 22% dan perhitungan Pajak Tangguhan (Deferred Tax Asset/Liability) sesuai PSAK 46 berdasarkan beda temporer koreksi fiskal.',
                'tax_implications' => 'Wajib diterapkan pada seluruh perhitungan faktur pajak keluaran PPN 11%, bukti potong PPh unifikasi, dan pelaporan SPT Tahunan Badan Form 1771.',
                'keywords' => ['uu hpp', 'ppn 11', 'ppn 12', 'pph badan 22', 'fasilitas 31e', 'nik npwp', 'psak 46', 'natura'],
                'official_source_url' => 'https://jdih.kemenkeu.go.id/fullText/2021/7TAHUN2021UU.pdf',
            ],
            [
                'category' => 'pajak',
                'level' => 'Peraturan Pemerintah',
                'code' => 'PP-58-2023-TER-PPH21',
                'number' => 'PP No. 58 Tahun 2023',
                'year' => 2023,
                'title' => 'Tarif Pemotongan PPh Pasal 21 atas Penghasilan Sehubungan dengan Pekerjaan, Jasa, atau Kegiatan',
                'about' => 'Penerapan Skema Tarif Efektif Rata-Rata (TER) Bulanan dan Harian PPh Pasal 21 Karyawan',
                'status' => 'berlaku',
                'effective_date' => '2024-01-01',
                'summary' => 'Mengatur skema penyederhanaan pemotongan PPh Pasal 21 untuk masa pajak Januari s.d November menggunakan tabel TER Bulanan (Kategori A, B, C) berdasarkan status PTKP dan rentang penghasilan bruto, serta perhitungan ulang menggunakan Tarif Pasal 17 pada masa Desember.',
                'key_points' => [
                    'TER Bulanan Kategori A: Untuk status PTKP TK/0, TK/1, K/0 (Tarif 0% s.d 34%).',
                    'TER Bulanan Kategori B: Untuk status PTKP TK/2, TK/3, K/1, K/2 (Tarif 0% s.d 34%).',
                    'TER Bulanan Kategori C: Untuk status PTKP K/3 (Tarif 0% s.d 34%).',
                    'Masa Pajak Terakhir (Desember): PPh 21 dihitung ulang setahun dengan Tarif Progresif Pasal 17 ayat (1) huruf a UU PPh, dikurangi total PPh 21 yang telah dipotong masa Jan-Nov.',
                ],
                'accounting_implications' => 'Jurnal Gaji Bulanan: [Debit] Beban Gaji & Upah (Gross), [Kredit] Utang PPh 21 (TER), [Kredit] Kas/Bank (Take Home Pay).',
                'tax_implications' => 'Wajib membuat Bukti Potong Formulir 1721-VIII untuk bulanan dan Formulir 1721-A1 untuk tahunan pada sistem e-Bupot 21/26 DJP.',
                'keywords' => ['pph 21', 'ter', 'tarif efektif rata-rata', 'ptkp', 'kategori a b c', 'masa desember', 'gaji', 'bupot 21'],
                'official_source_url' => 'https://jdih.kemenkeu.go.id/download/1f034cb7-fc37-4f65-8b83-a4f61fbb7c66/PP%20Nomor%2058%20Tahun%202023.pdf',
            ],
            [
                'category' => 'pajak',
                'level' => 'Peraturan Pemerintah',
                'code' => 'PP-55-2022-PENYESUAIAN-PPH',
                'number' => 'PP No. 55 Tahun 2022',
                'year' => 2022,
                'title' => 'Penyesuaian Pengaturan di Bidang Pajak Penghasilan',
                'about' => 'Pelaksanaan UU HPP terkait Objek PPh, Natura, Anti-Tax Avoidance, Beneficial Ownership, dan Penilaian Kembali Aktiva',
                'status' => 'berlaku',
                'effective_date' => '2022-12-20',
                'summary' => 'Peraturan pemerintah turunan UU HPP yang merinci batasan natura yang dikecualikan dari objek pajak, aturan pencegahan penghindaran pajak (transfer pricing, thin capitalization / DER ratio), dan perlakuan instrumen derivatif.',
                'key_points' => [
                    'Biaya natura dan kenikmatan dapat dikurangkan dari penghasilan bruto (deductible) sepanjang merupakan biaya 3M (Mendapatkan, Menagih, Memelihara penghasilan).',
                    'Pengecualian objek PPh bagi pegawai atas natura fasilitas kerja krusial seperti makanan/minuman seluruh pegawai, seragam keselamatan, dan fasilitas di daerah tertentu.',
                    'Pencegahan penghindaran pajak dengan debt-to-equity ratio (DER) maksimal 4:1 untuk pengakuan beban bunga.',
                ],
                'accounting_implications' => 'Biaya natura non-objek dicatat sebagai Beban Operasional Umum. Beban bunga yang melebihi rasio DER 4:1 wajib dilakukan koreksi fiskal positif.',
                'tax_implications' => 'Pemberi kerja wajib memotong PPh 21 atas natura/kenikmatan di luar daftar pengecualian mulai masa Juli 2023.',
                'keywords' => ['natura', 'kenikmatan', 'deductible', 'koreksi fiskal', 'transfer pricing', 'der 4:1', 'biaya bunga'],
                'official_source_url' => 'https://jdih.kemenkeu.go.id/download/2353cfc5-9273-45f8-8c01-729938b81308/55~PP~2022.pdf',
            ],

            // ==========================================
            // KATEGORI: PERATURAN MENTERI KEUANGAN (PMK)
            // ==========================================
            [
                'category' => 'pmk',
                'level' => 'Peraturan Menteri Keuangan',
                'code' => 'PMK-168-2023-JUKNIS-TER',
                'number' => 'PMK No. 168 Tahun 2023',
                'year' => 2023,
                'title' => 'Petunjuk Pelaksanaan Pemotongan Pajak atas Penghasilan Sehubungan dengan Pekerjaan, Jasa, atau Kegiatan',
                'about' => 'Petunjuk Teknis Lengkap, Contoh Perhitungan Praktis, dan Tata Cara Pemotongan PPh Pasal 21 TER',
                'status' => 'berlaku',
                'effective_date' => '2024-01-01',
                'summary' => 'Pedoman teknis resmi DJP bagi perusahaan untuk menghitung PPh 21 atas pegawai tetap, pegawai tidak tetap, bukan pegawai (freelancer), dewan komisaris, dan peserta kegiatan, dilengkapi puluhan lampiran contoh hitung.',
                'key_points' => [
                    'Pegawai Tetap bulanan: Penghasilan Bruto x Tarif TER Kategori A/B/C.',
                    'Bukan Pegawai / Tenaga Ahli: 50% x Penghasilan Bruto x Tarif Pasal 17 (tanpa syarat berkesinambungan).',
                    'Komisaris Non-Aktif: Penghasilan Bruto Kumulatif x Tarif Pasal 17.',
                    'Peserta Kegiatan / Hadiah: Penghasilan Bruto x Tarif Pasal 17.',
                ],
                'accounting_implications' => 'Perusahaan perlu memisahkan pencatatan akun Utang PPh 21 Karyawan Tetap dan Utang PPh 21 Jasa Tenaga Ahli/Bukan Pegawai untuk memudahkan rekonsiliasi GL dengan e-Bupot.',
                'tax_implications' => 'Pemotong pajak wajib memberikan Bukti Potong 1721-VIII paling lambat akhir bulan berikutnya setelah masa pajak berakhir.',
                'keywords' => ['juknis pph 21', 'pmk 168', 'bukan pegawai', 'tenaga ahli', '50 persen', 'komisaris', 'e-bupot 21'],
                'official_source_url' => 'https://jdih.kemenkeu.go.id/download/ef247e62-cff3-4b6a-9bb7-380d60317e08/PMK%20Nomor%20168%20Tahun%202023.pdf',
            ],
            [
                'category' => 'pmk',
                'level' => 'Peraturan Menteri Keuangan',
                'code' => 'PMK-41-2022-PPH22-IMPOR',
                'number' => 'PMK No. 41/PMK.010/2022',
                'year' => 2022,
                'title' => 'Perubahan Kedua atas PMK No. 34/PMK.010/2017 tentang Pemungutan PPh Pasal 22 Terkait Impor',
                'about' => 'Tarif Pemungutan PPh Pasal 22 Impor, Komoditas Tertentu, Penggunaan API, dan Kriteria Pengecualian',
                'status' => 'berlaku',
                'effective_date' => '2022-03-30',
                'summary' => 'Mengatur secara rinci komponen tarif PPh Pasal 22 atas kegiatan impor barang ke dalam daerah pabean Indonesia berdasarkan kepemilikan Angka Pengenal Importir (API) serta jenis komoditas komersial.',
                'key_points' => [
                    'Importir memiliki API (Angka Pengenal Importir): Dikenakan PPh 22 sebesar 2,5% dari Nilai Impor (CIF + Bea Masuk).',
                    'Importir NON-API: Dikenakan PPh 22 sebesar 7,5% dari Nilai Impor.',
                    'Impor barang komoditas tertentu (Lampiran I): Tarif 10% dari Nilai Impor.',
                    'Impor kedelai, gandum, dan tepung terigu oleh importir ber-API: Tarif 0,5% dari Nilai Impor.',
                    'Impor yang tidak dikuasai / lelang kepabeanan: Tarif 7,5% dari harga jual lelang.',
                ],
                'accounting_implications' => 'PPh Pasal 22 Impor yang dibayar via SSPCP TIDAK BOLEH dibebankan ke HPP! Wajib dicatat di sisi DEBIT akun Aset Lancar: "Uang Muka PPh Pasal 22 (Prepaid Tax)" dan nantinya dikreditkan di SPT Tahunan.',
                'tax_implications' => 'PPh Pasal 22 Impor merupakan kredit pajak resmi yang mengurangi Pajak Terutang Badan di Induk SPT 1771 pada akhir tahun buku.',
                'keywords' => ['pph 22 impor', 'tarif 2.5 persen', 'tarif 7.5 persen', 'api', 'non api', 'nilai impor', 'kredit pajak', 'uang muka pph 22'],
                'official_source_url' => 'https://jdih.kemenkeu.go.id/download/1f523177-3e19-48e0-81f1-3eb2aa94a7cb/41~PMK.010~2022Per.pdf',
            ],
            [
                'category' => 'pmk',
                'level' => 'Peraturan Menteri Keuangan',
                'code' => 'PMK-66-2023-NATURA',
                'number' => 'PMK No. 66 Tahun 2023',
                'year' => 2023,
                'title' => 'Perlakuan Pajak Penghasilan atas Penggantian atau Imbalan dalam Bentuk Natura dan/atau Kenikmatan',
                'about' => 'Batasan Nilai dan Jenis Fasilitas Natura/Kenikmatan yang Dikecualikan dari Pemotongan PPh',
                'status' => 'berlaku',
                'effective_date' => '2023-07-01',
                'summary' => 'Menetapkan daftar jenis dan batasan tertentu fasilitas natura/kenikmatan yang bebas dari pemotongan PPh Pasal 21 karyawan serta ketentuan penilaian harga pasar / biaya riil.',
                'key_points' => [
                    'Makanan/minuman bagi seluruh pegawai di tempat kerja: Bebas PPh tanpa batasan nilai.',
                    'Kupon makan/reimbursement makan lembur bagi pegawai dinas luar: Bebas PPh s.d Rp 2.000.000 per bulan.',
                    'Bingkisan hari raya keagamaan (Lebaran/Natal): Bebas PPh untuk seluruh pegawai tanpa batas nominal.',
                    'Bingkisan selain hari raya: Bebas PPh s.d Rp 3.000.000 per tahun per pegawai.',
                    'Peralatan/fasilitas kerja (laptop, komputer, ponsel pintar, pulsa/internet kantor): Bebas PPh tanpa batasan nilai.',
                    'Fasilitas tempat tinggal komunal (mess/asrama): Bebas PPh tanpa batas nilai.',
                ],
                'accounting_implications' => 'Seluruh pengeluaran natura yang memenuhi syarat 3M dapat dibiayakan secara komersial dan fiskal tanpa perlu dikoreksi fiskal positif.',
                'tax_implications' => 'Fasilitas di atas ambang batas (misal kendaraan dinas komisaris atau sewa rumah ekspatriat) selisih lebihnya wajib dipotong PPh 21 pada slip gaji.',
                'keywords' => ['natura', 'kenikmatan', 'kupon makan', 'laptop kantor', 'bingkisan lebaran', 'pmk 66', 'non objek pph'],
                'official_source_url' => 'https://jdih.kemenkeu.go.id/download/f285d852-520e-43f1-b99b-0298a0029b9f/66%20TAHUN%202023.pdf',
            ],
            [
                'category' => 'pmk',
                'level' => 'Peraturan Menteri Keuangan',
                'code' => 'PMK-81-2024-CORETAX',
                'number' => 'PMK No. 81 Tahun 2024',
                'year' => 2024,
                'title' => 'Ketentuan Perpajakan dalam Rangka Pelaksanaan Sistem Inti Administrasi Perpajakan (Coretax)',
                'about' => 'Integrasi Layanan Perpajakan Terpadu, Deposit Pajak (Tax Account), dan Pembaruan Format Dokumen Fiskal',
                'status' => 'berlaku',
                'effective_date' => '2025-01-01',
                'summary' => 'Payung hukum operasional Coretax DJP. Mengatur penggunaan Taxpayer Account Management (TAM), sistem deposit pajak terpadu, interoperabilitas e-Faktur dan e-Bupot secara terintegrasi satu pintu.',
                'key_points' => [
                    'Wajib Pajak memiliki Akun Deposit Pajak untuk pembayaran seluruh jenis pajak secara terpadu tanpa perlu membuat banyak kode billing terpisah.',
                    'Penyampaian SPT Masa Unifikasi dan SPT PPN terpusat melalui Coretax Portal.',
                    'Sinkronisasi otomatis PIB dari Ditjen Bea Cukai ke Coretax DJP untuk pre-populated Pajak Masukan impor.',
                ],
                'accounting_implications' => 'Deposit pajak di Coretax dicatat di neraca perusahaan sebagai akun aset lancar "Kas di Bank - Rekening Deposit Pajak DJP".',
                'tax_implications' => 'Sistem AKRU siap menghasilkan file ekspor XML/JSON dengan schema resmi Coretax untuk proses upload massal otomatis.',
                'keywords' => ['coretax', 'pmk 81', 'tax account', 'deposit pajak', 'prepopulated', 'insw', 'spt terpadu'],
                'official_source_url' => 'https://jdih.kemenkeu.go.id/download/coretax-pmk81-2024.pdf',
            ],

            // ==========================================
            // KATEGORI: STANDAR AKUNTANSI KEUANGAN (SAK/PSAK)
            // ==========================================
            [
                'category' => 'akuntansi',
                'level' => 'Standar Akuntansi Keuangan',
                'code' => 'PSAK-1-PENYAJIAN',
                'number' => 'PSAK No. 1 (Revisi)',
                'year' => 2020,
                'title' => 'Penyajian Laporan Keuangan',
                'about' => 'Dasar Penyajian, Komponen Laporan Keuangan Lengkap, dan Asumsi Kelangsungan Usaha (Going Concern)',
                'status' => 'berlaku',
                'effective_date' => '2020-01-01',
                'summary' => 'Menetapkan dasar-dasar penyajian laporan keuangan bertujuan umum agar dapat dibandingkan baik dengan laporan keuangan periode sebelumnya maupun dengan laporan keuangan entitas lain.',
                'key_points' => [
                    'Laporan keuangan lengkap terdiri atas: Laporan Posisi Keuangan (Neraca), Laporan Laba Rugi dan Penghasilan Komprehensif Lain, Laporan Perubahan Ekuitas, Laporan Arus Kas, dan Catatan atas Laporan Keuangan (CaLK).',
                    'Asumsi dasar: Akuntansi Berbasis Akrual (Accrual Basis) dan Kelangsungan Usaha (Going Concern).',
                    'Pemisahan pos Lancar (Current) dan Tidak Lancar (Non-Current) pada aset dan liabilitas.',
                    'Saling hapus (off-setting) aset dan liabilitas dilarang kecuali disyaratkan atau diizinkan oleh SAK.',
                ],
                'accounting_implications' => 'Seluruh modul pelaporan AKRU (Neraca, Laba Rugi, Arus Kas) disusun mengacu pada format taksonomi dan hierarki akun PSAK 1.',
                'tax_implications' => 'Laporan keuangan komersial berbasis PSAK 1 menjadi titik awal lampiran SPT Tahunan PPh Badan sebelum dilakukan koreksi fiskal.',
                'keywords' => ['psak 1', 'penyajian laporan keuangan', 'neraca', 'laba rugi', 'arus kas', 'calk', 'basis akrual'],
                'official_source_url' => 'https://iaiglobal.or.id/sak-indonesia',
            ],
            [
                'category' => 'akuntansi',
                'level' => 'Standar Akuntansi Keuangan',
                'code' => 'PSAK-16-ASET-TETAP',
                'number' => 'PSAK No. 16 (Revisi)',
                'year' => 2020,
                'title' => 'Aset Tetap (Property, Plant, and Equipment)',
                'about' => 'Pengakuan, Pengukuran Biaya Perolehan, Penyusutan, dan Pelepasan Aset Tetap',
                'status' => 'berlaku',
                'effective_date' => '2020-01-01',
                'summary' => 'Mengatur perlakuan akuntansi untuk aset tetap agar pengguna laporan keuangan dapat memahami informasi mengenai investasi entitas dalam aset tetap dan perubahan dalam investasi tersebut.',
                'key_points' => [
                    'Biaya perolehan mencakup harga beli, bea impor, pajak pembelian yang tidak dapat dikreditkan, dan seluruh biaya yang dapat diatribusikan langsung sampai aset siap digunakan.',
                    'Penyusutan dialokasikan secara sistematis selama masa manfaat aset (Metode Garis Lurus, Saldo Menurun, atau Jumlah Unit Produksi).',
                    'Tanah secara umum memiliki masa manfaat tak terbatas sehingga tidak disusutkan.',
                ],
                'accounting_implications' => 'Modul Fixed Assets AKRU otomatis menghitung jurnal amortisasi bulanan: [Debit] Beban Penyusutan, [Kredit] Akumulasi Penyusutan.',
                'tax_implications' => 'Terdapat beda masa manfaat fiskal (Pasal 11 UU PPh Kelompok 1, 2, 3, 4) dengan masa manfaat komersial yang menimbulkan koreksi fiskal positif/negatif.',
                'keywords' => ['psak 16', 'aset tetap', 'penyusutan', 'garis lurus', 'bea impor kapitalisasi', 'masa manfaat fiskal'],
                'official_source_url' => 'https://iaiglobal.or.id/sak-indonesia',
            ],
            [
                'category' => 'akuntansi',
                'level' => 'Standar Akuntansi Keuangan',
                'code' => 'PSAK-73-SEWA',
                'number' => 'PSAK No. 73',
                'year' => 2020,
                'title' => 'Sewa (Leases)',
                'about' => 'Pencatatan Sewa bagi Penyewa (Lessee) dengan Pengakuan Hak Guna Aset dan Liabilitas Sewa',
                'status' => 'berlaku',
                'effective_date' => '2020-01-01',
                'summary' => 'Mengeliminasi klasifikasi sewa operasi vs pembiayaan bagi penyewa (lessee). Hampir seluruh kontrak sewa jangka panjang (sewa ruko, gedung kantor, mesin) wajib diakui di neraca sebagai Hak Guna Aset (Right-of-Use Asset) dan Liabilitas Sewa.',
                'key_points' => [
                    'Penyewa wajib mengakui Aset Hak Guna (ROU Asset) dan Liabilitas Sewa pada tanggal permulaan sewa sebesar nilai kini dari pembayaran sewa masa depan.',
                    'Pengecualian (dapat dicatat sebagai beban garis lurus): Sewa jangka pendek (<= 12 bulan) dan sewa aset bernilai rendah (low-value assets).',
                    'Beban sewa terbagi menjadi Beban Penyusutan Aset ROU dan Beban Bunga Liabilitas Sewa.',
                ],
                'accounting_implications' => 'Jurnal Awal: [Debit] Aset Hak Guna (ROU), [Kredit] Liabilitas Sewa. Jurnal Pembayaran: [Debit] Liabilitas Sewa, [Debit] Beban Bunga, [Kredit] Kas/Bank.',
                'tax_implications' => 'Secara pajak, pembayaran sewa gedung dipotong PPh Pasal 4 ayat (2) Final 10% dan diakui sebagai biaya sesuai masa manfaat sewa riil.',
                'keywords' => ['psak 73', 'sewa', 'right of use', 'rou asset', 'liabilitas sewa', 'sewa ruko', 'pph 4 ayat 2'],
                'official_source_url' => 'https://iaiglobal.or.id/sak-indonesia',
            ],
            [
                'category' => 'akuntansi',
                'level' => 'Standar Akuntansi Keuangan',
                'code' => 'PSAK-71-INSTRUMEN-KEUANGAN',
                'number' => 'PSAK No. 71',
                'year' => 2020,
                'title' => 'Instrumen Keuangan (Financial Instruments)',
                'about' => 'Klasifikasi, Pengukuran, dan Cadangan Kerugian Penurunan Nilai Piutang Berbasis Kerugian Ekspektasian (ECL)',
                'status' => 'berlaku',
                'effective_date' => '2020-01-01',
                'summary' => 'Mengubah model penurunan nilai piutang usaha dari model kerugian yang telah terjadi (incurred loss) menjadi model kerugian kredit ekspektasian (Expected Credit Loss / ECL) yang bersifat forward-looking.',
                'key_points' => [
                    'Piutang usaha wajib dievaluasi potensi gagal bayarnya menggunakan matriks provisi umur piutang (Aging Matrix).',
                    'Penyisihan piutang tak tertagih dibentuk sejak awal timbulnya piutang, bukan menunggu pelanggan bangkrut/default.',
                ],
                'accounting_implications' => 'AKRU Aging Report mendukung penentuan cadangan ECL: [Debit] Beban Cadangan Kerugian Penurunan Nilai, [Kredit] Cadangan Piutang Tak Tertagih.',
                'tax_implications' => 'Secara fiskal, cadangan piutang tidak boleh dibiayakan (koreksi fiskal positif), kecuali telah nyata-nyata dihapuskan sesuai syarat Pasal 9 ayat (1) huruf c UU PPh.',
                'keywords' => ['psak 71', 'ecl', 'expected credit loss', 'piutang ragu-ragu', 'penyisihan piutang', 'koreksi fiskal cadangan'],
                'official_source_url' => 'https://iaiglobal.or.id/sak-indonesia',
            ],
            [
                'category' => 'akuntansi',
                'level' => 'Standar Akuntansi Keuangan',
                'code' => 'PSAK-72-PENDAPATAN',
                'number' => 'PSAK No. 72',
                'year' => 2020,
                'title' => 'Pendapatan dari Kontrak dengan Pelanggan',
                'about' => 'Model 5 Langkah Pengakuan Pendapatan dan Pemisahan Kewajiban Pelaksanaan',
                'status' => 'berlaku',
                'effective_date' => '2020-01-01',
                'summary' => 'Menyatukan standar pengakuan pendapatan penjualan barang dan penyerahan jasa ke dalam satu kerangka kerja komprehensif berbasis 5 langkah (5-step model).',
                'key_points' => [
                    'Langkah 1: Identifikasi kontrak dengan pelanggan.',
                    'Langkah 2: Identifikasi kewajiban pelaksanaan (Performance Obligations) dalam kontrak.',
                    'Langkah 3: Menentukan harga transaksi (Transaction Price).',
                    'Langkah 4: Mengalokasikan harga transaksi terhadap setiap kewajiban pelaksanaan.',
                    'Langkah 5: Mengakui pendapatan saat (atau selama) entitas menyelesaikan kewajiban pelaksanaan.',
                ],
                'accounting_implications' => 'Uang muka penjualan yang diterima sebelum barang diserahkan dicatat sebagai "Pendapatan Diterima di Muka / Liabilitas Kontrak", bukan sebagai pendapatan penjualan langsung.',
                'tax_implications' => 'Faktur Pajak PPN wajib diterbitkan saat penyerahan BKP/JKP atau saat penerimaan pembayaran (mana yang lebih dulu terjadi).',
                'keywords' => ['psak 72', 'pendapatan', '5 langkah pengakuan', 'performance obligation', 'uang muka penjualan'],
                'official_source_url' => 'https://iaiglobal.or.id/sak-indonesia',
            ],

            // ==========================================
            // KATEGORI: SURAT EDARAN (SE DJP & DJBC)
            // ==========================================
            [
                'category' => 'surat_edaran',
                'level' => 'Surat Edaran',
                'code' => 'SE-05-PJ-2022-PENGAWASAN',
                'number' => 'SE-05/PJ/2022',
                'year' => 2022,
                'title' => 'Pengawasan Kepatuhan Wajib Pajak Pasca UU HPP',
                'about' => 'Strategi Pengawasan Berbasis Analisis Risiko (Compliance Risk Management / CRM) dan Pengujian Ekualisasi',
                'status' => 'berlaku',
                'effective_date' => '2022-02-10',
                'summary' => 'Pedoman bagi Account Representative (AR) kantor pajak dalam melakukan analisis risiko kepatuhan wajib pajak melalui ekualisasi omzet penjualan di SPT Tahunan vs SPT Masa PPN, serta ekualisasi biaya gaji vs SPT PPh 21.',
                'key_points' => [
                    'Penerbitan Surat Permintaan Penjelasan atas Data dan/atau Keterangan (SP2DK) dipicu oleh selisih ekualisasi omzet dan biaya.',
                    'Kriteria anomali fiskal: Beban gaji pada laporan keuangan tidak sesuai dengan dasar pengenaan pajak (DPP) SPT Masa PPh 21.',
                    'Ekualisasi PPh 23: Beban jasa dan sewa pada laporan laba rugi dicocokkan dengan bukti potong PPh 23 terbit.',
                ],
                'accounting_implications' => 'Menu Tax Audit Package pada sistem AKRU menyediakan kertas kerja otomatis yang mensimulasikan uji ekualisasi DJP ini.',
                'tax_implications' => 'Menjadi panduan wajib pajak dalam merespons SP2DK dengan melampirkan rekonsiliasi buku besar.',
                'keywords' => ['sp2dk', 'crm', 'ekualisasi omzet', 'ekualisasi gaji', 'se 05 pj 2022', 'account representative'],
                'official_source_url' => 'https://pajak.go.id',
            ],
            [
                'category' => 'surat_edaran',
                'level' => 'Surat Edaran',
                'code' => 'SE-11-BC-2023-PEMERIKSAAN-IMPOR',
                'number' => 'SE-11/BC/2023',
                'year' => 2023,
                'title' => 'Standardisasi Pemeriksaan Fisik dan Penelitian Dokumen Impor Barang',
                'about' => 'Prosedur Pemeriksaan Jalur Kuning, Merah, dan Notul (Nota Pembetulan) Bea Masuk Tambahan',
                'status' => 'berlaku',
                'effective_date' => '2023-06-15',
                'summary' => 'Petunjuk teknis pejabat fungsional pemeriksa bea cukai dalam meneliti kebenaran tarif HS Code dan nilai pabean yang diberitahukan dalam PIB.',
                'key_points' => [
                    'Penetapan tarif dan nilai pabean (SPTNP/Notul) diterbitkan jika terdapat selisih bayar bea masuk dan pajak impor.',
                    'Importir berhak mengajukan keberatan pabean dalam jangka waktu 60 hari kerja sejak tanggal SPTNP.',
                ],
                'accounting_implications' => 'Tagihan kekurangan bayar Bea Masuk (Notul/SPTNP) dicatat sebagai beban denda/kekurangan pabean atau penambah nilai persediaan jika barang belum terjual.',
                'tax_implications' => 'Tagihan PPN Impor dan PPh 22 pada SPTNP yang dilunasi dengan Surat Bukti Pembayaran (SSPCP) tetap dapat dikreditkan.',
                'keywords' => ['sptnp', 'notul', 'pemeriksaan fisik', 'bea cukai', 'keberatan pabean', 'jalur merah'],
                'official_source_url' => 'https://beacukai.go.id',
            ],
        ];

        foreach ($regulations as $reg) {
            Regulation::updateOrCreate(
                ['code' => $reg['code']],
                $reg
            );
        }
    }
}
